### PR TITLE
Print multiline log messages (fixes #3)

### LINKED ISSUE #3: Multiline log messages are printed incorrectly
Log messages containing newlines are printed like this: (using the termion backend)
```
line1
     line2
          line3
```

I fixed the issue myself (WIP: https://github.com/FliegendeWurst/cursive-flexi-logger-view/commit/b2a84f625559c4d019240844d2c58373c3de2ee9) and will open a PR soon.

### PR DESCRIPTION
**Pull request by FliegendeWurst**
Implemented as suggested here: https://github.com/deinstapel/cursive-flexi-logger-view/pull/5#issuecomment-616413663 (issue #3)
Example:
```
DEBUG <src/main:46> first line
                    second line
```
Alternatively, it would now be trivial to implement (l.210: add `x = 0`) this format (which is consistent with FlexiLogger):
```
DEBUG <src/main:46> first line
second line
```

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -197,10 +220,22 @@ impl View for FlexiLoggerView {
         // The longest line sets the width
         let w = logs
             .iter()
-            .map(|msg| msg.width())
+            .map(|msg|
+                msg.spans().map(|x|
+                    // if the log message contains more than one line,
+                    // only the longest line should be considered
+                    // (definitely not the total content.len())
+                    x.content.split('\n').map(|x| x.len()).max().unwrap()
```
Comment (gyscos) [inline src/lib.rs]: Should still use [`x.width()`](https://docs.rs/unicode-width/0.1.8/unicode_width/trait.UnicodeWidthStr.html) instead of `x.len()` to account for multi-byte characters ;).

Comment (fin-ger) [reply src/lib.rs]: Yes, this is also broken in my previous implementation. Thanks for the hint!

File: src/lib.rs [hunk 2]
```diff
@@ -197,10 +221,22 @@ impl View for FlexiLoggerView {
         // The longest line sets the width
         let w = logs
             .iter()
-            .map(|msg| msg.width())
+            .map(|msg|
+                msg.spans().map(|x|
+                    // if the log message contains more than one line,
+                    // only the longest line should be considered
+                    // (definitely not the total content.len())
+                    x.content.split('\n').map(|x| x.width()).max().unwrap()
```
Comment (gyscos) [inline src/lib.rs]: Nit: if a `span` is empty, this would panic. "Spans are never empty" is a possible invariant, but a bit less obvious to validate.
Maybe `unwrap_or(0)` instead?

File: src/lib.rs [hunk 3]
```diff
@@ -197,10 +221,22 @@ impl View for FlexiLoggerView {
...
+                ).sum::<usize>()
```
Comment (gyscos) [inline src/lib.rs:230]: Wait - do you really want the _sum_ of the longest line of each span?
For example, if you have 3 spans:
* `"a b c"`
* `" d\ne f"`
* `"g"`
Then the text would look like:
```
a b c d
e f g
```
And the width should be the maximum line width _across_ spans: the width of `"a b c d"`, not the width of `"a b c"` + the width of `"e f"` + the width of `"g"`.

File: src/lib.rs (hunk 2 above)
Comment (FliegendeWurst) [reply src/lib.rs]: In that case `"".split('\n')` would consist of `""` and `.max()` would return Some(0).

**Comment by fia0** [comment]
Hi FliegendeWurst,
finally I have some time for this crate, first of all very sorry for the long waiting time this PR has been on hold.
The result looks really nice! The code as-is is ready to merge.

As for the indentation, I thought a bit about it and since it's only a small option we can make it with a few tweaks customizable.
I pushed on your branch a suggestion on how to add this. Allowing for `FlexiLoggerView` still to be created via `scrollable` but adding a trait `Indentable` on `ScrollView<FlexiLoggerView>` to change the indentation afterwards with `indent` and `no_indent`.
The indented variant would stay as default, but can be easily changed:
```rust
use flexi_logger_view::{FlexiLoggerView, Indentable};
let v = FlexiLoggerView::scrollable().no_indent();
```
I think solving it like this allows both variants to be used easily.
You can revert the commit if you like, just a proposal for implementation.

@fin-ger Are you on-board with an introduction like this?

**Comment by fia0** [comment]
Okay then, seems everyone is on board with these changes. I'll merge them to master and see to release the new version today.
Thanks again to everyone for working on this :D
